name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Generate Docs
        run: cargo doc --no-deps
      - name: Prepare docs
        run: |
          mkdir -p ./gh-pages/doc
          cp -r ./target/doc/* ./gh-pages/doc/
          echo '<meta http-equiv="refresh" content="0; url=doc/your_crate_name/index.html">' > ./gh-pages/index.html
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
